Edura/Components/CartSummaryViewComponent.cs
using Edura.WebUI.Infrastructure;
using Edura.WebUI.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Edura.WebUI.Components
{
    public class CartSummaryViewComponent:ViewComponent
    {
        public string Invoke()
        {
           return HttpContext.Session.GetJson<Cart>("Cart")?.Products.Count().ToString() ?? "0";
            
        }
    }
}

Edura/Views/Shared/_AdminLayout.cshtml

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AdminLayout</title>
</head>
<body>
</body>
</html>

Edura/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from demos.codeniner.com/edura/shop-catalog-sidebar-left.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 13 Jul 2017 15:11:18 GMT -->
<head>
    <!-- METAS -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- TITLE -->
    <title>Edura - Multipurpose Website Template</title>

    <!-- FAVICON -->
    <link rel="shortcut icon" href="images/favicon.png" />

    <link href="~/css/bundle.css" rel="stylesheet" />
</head>

<body>

    <!-- WRAPPER START -->
    <div id="wrapper">
        <!-- HEADER START -->
        <section id="header">
            <!-- Fixed navbar -->
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">
                            <img src="/images/edura-logo.png" alt="Edura - Multipurpose Website Template">
                        </a>
                    </div>
                    <div id="navbar" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            @if (User.Identity.IsAuthenticated)
                            {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" role="button" aria-haspopup="true" aria-expanded="false">@User.Identity.Name</a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Account</a></li>
                                <li><a asp-controller="Account" asp-action="Logout">Logout</a></li>
                            </ul>
                        </li> }
                                    else
                                    {
                        <li><a asp-controller="Account" asp-action="Login"><i class="fa fa-user-o "></i>Login</a></li>
}
                            }
                            <li><a asp-controller="Cart" asp-action="Index"><i class="fa fa-shopping-cart fa-fw"></i> Cart (@await Component.InvokeAsync("CartSummary"))</a></li>
                        </ul>


                       

                    </div><!--/.nav-collapse -->
                </div>
            </nav>
        </section>
        <!-- HEADER END -->
        <!-- PAGE TITLE START -->
        <section id="title" class="container-fluid wow fadeInDown">
            <div class="container">
                <div class="row">
                    <div class="col-xs-6">
                        <h1>Shop <small>Catalog</small></h1>
                    </div>
                    <div class="col-xs-6 text-right breadcrumbs">
                        <ul class="list-inline list-unstyled">
                            <li><a href="index-2.html">Home</a></li>
                            <li>/</li>
                            <li>Shop</li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
        <!-- PAGE TITLE END -->
        <!-- CONTENT START -->

        @RenderBody()

        <!-- CONTENT END -->
        <!-- FOOTER START -->
        <section id="footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-3">
                        <img src="/images/edura-logo.png" alt="Edura - Multipurpose Website Template">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. <b>Lorem ipsum dolor sit amet, consectetur adipiscing</b>.</p>
                        <br>
                        <ul class="list-unstyled list-inline social-icons">
                            <li><a href="#" class="facebook"><i class="fa fa-facebook facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter twitter"></i></a></li>
                            <li><a href="#" class="googleplus"><i class="fa fa-google-plus googleplus"></i></a></li>
                            <li><a href="#" class="youtube"><i class="fa fa-youtube youtube"></i></a></li>
                            <li><a href="#" class="linkedin"><i class="fa fa-linkedin linkedin"></i></a></li>
                        </ul>
                    </div>
                    <div class="col-md-3">
                        <h4>PAGES</h4>
                        <ul class="list-unstyled">
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">HOME</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">ABOUT US</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">SERVICES</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">BLOG</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">STORE</a></li>
                            <li><i class="fa fa-caret-right fa-fw" aria-hidden="true"></i> <a href="#">PRIVACY POLICY</a></li>
                        </ul>
                    </div>

                    <div class="col-md-3">
                        <h4>CONTACT US</h4>
                        <p><i class="fa fa-map-pin fa-fw"></i> 379 5th Ave, New York, 10001, USA</p>
                        <p><i class="fa fa-phone fa-fw"></i> +(112) 345 6879</p>
                        <p><i class="fa fa-phone fa-fw"></i> +(112) 345 6879</p>
                        <p><i class="fa fa-envelope fa-fw"></i> hello@example.com</p>
                    </div>

                    <div class="col-md-3">
                        <h4>NEWSLETTER</h4>
                        <p>Subscribe to our monthly newsletter and stay updated with the latest news and info.</p>
                        <form action="#" method="post">
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon"><i class="fa fa-envelope-o"></i></div>
                                    <input type="email" class="form-control" id="email" placeholder="Your Email Address" required>
                                </div>
                            </div>
                            <div class="form-group pull-right">
                                <button type="submit" class="btn btn-primary">Subscribe</button>
                            </div>
                        </form>
                    </div>
                </div>

                <div class="row">
                    <hr>
                    <div class="col-md-12 text-center bottom">
                        <p>Copyright &copy; 2016 Codeniner. All rights reserved.</p>
                    </div>
                </div>
            </div>
        </section>
        <!-- FOOTER END -->


    </div>
    <!-- WRAPPER END -->
    <!-- back to top button -->
    <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button" title="Click to return on the top page" data-toggle="tooltip" data-placement="left"><span class="glyphicon glyphicon-chevron-up"></span></a>


    <script src="~/js/bundle.js"></script>


    <script>
    (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '../../www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-81122143-3', 'auto');
        ga('send', 'pageview');</script>

    <!-- STYLE SWITCHER -->
    <script src="demo/demo.js"></script>
    <div id="styleswitcher">
        <input id="settings-btn" class="settings-btn" type="checkbox">
        <label for="settings-btn" class="settings-box-element"><i class="fa fa-2x fa-gear"></i></label>
        <div class="buttons-wrapper settings-box-element">
            <h4 class="text-uppercase">Change Color Style</h4>
            <p><button id="demo-lunar" class="btn demo-btn demo-lunar">Lunar (Default)</button></p>
            <p><button id="demo-blue" class="btn demo-btn demo-blue">Blue</button></p>
            <p><button id="demo-green" class="btn demo-btn demo-green">Green</button></p>
            <p><button id="demo-red" class="btn demo-btn demo-red">Red</button></p>
            <p><button id="demo-orange" class="btn demo-btn demo-orange">Orange</button></p>
        </div>
    </div>

</body>

<!-- Mirrored from demos.codeniner.com/edura/shop-catalog-sidebar-left.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 13 Jul 2017 15:11:18 GMT -->
</html>

Edura/Views/Shared/_ProductItem.cshtml
@model Product


<div class="col-md-4 wow fadeInUp" style="visibility: visible; animation-name: fadeInUp;">
    <div class="text-center product-item">
        <div class="product-item-top">
            <img alt="" class="img-responsive" src="/images/products/@Model.Image">
            <div class="mask"></div>
            <ul class="list-unstyled list-inline">
                <li><a href="/Product/Details/@Model.ProductId"><i class="fa fa-link fa-fw"></i></a></li>
                <li><a href="#"><i class="fa fa-cart-plus fa-fw"></i></a></li>
            </ul>
        </div>
        <div class="product-item-inner">
            <h3 class="product-title"><a href="/Product/Details/@Model.ProductId">@Model.ProductName</a></h3>
            <p class="product-price">@Model.Price ₺</p>
        </div>
    </div>
</div>